apiVersion: v1
kind: Service
metadata:
  name: analytics-runtime
  labels:
    app: analytics-runtime
spec:
  type: LoadBalancer
  selector:
    app: analytics-runtime
  ports:
    - name: rest
      port: 80
      targetPort: 8000
      protocol: TCP
      appProtocol: http
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP
      appProtocol: grpc
